# Maps the tuple of (folder_name/node_name, column_name) to a target key (used for renaming columns)
ShardMapping = {
    # segmentation types (mvad)
    ("v4-vad_ws_mvad", "raw.vad.npy"): "v4-vad_ws_mvad.raw.vad.npy",
    ("v4-vad_ws_mvad", "eq.vad.npy"): "v4-vad_ws_mvad.eq.vad.npy",
    ("v4-vad_ws_mvad", "max.vad.npy"): "v4-vad_ws_mvad.max.vad.npy",
    ("v4-vad_ws_continuous_mvad", "raw.vad.npy"): "v4-vad_ws_continuous_mvad.raw.vad.npy",
    ("v4-vad_ws_continuous_mvad", "eq.vad.npy"): "v4-vad_ws_continuous_mvad.eq.vad.npy",
    ("v4-vad_ws_continuous_mvad", "max.vad.npy"): "v4-vad_ws_continuous_mvad.max.vad.npy",
    ("v3-vad_ws_mvad", "raw.vad.npy"): "v3-vad_ws_mvad.raw.vad.npy",
    ("v3-vad_ws_mvad", "eq.vad.npy"): "v3-vad_ws_mvad.eq.vad.npy",
    ("v3-vad_ws_mvad", "max.vad.npy"): "v3-vad_ws_mvad.max.vad.npy",
    ("v5-diarized_continuous_mvad", "diarized.vad.npy"): "v5-diarized_continuous_mvad.diarized.vad.npy",
    ("v5-diarized_continuous_mvad", "diarized.pause_dur.npy"): "v5-diarized_continuous_mvad.diarized.pause_dur.npy",
    (
        "v5-diarized_continuous_mvad",
        "diarized.pause_energy.npy",
    ): "v5-diarized_continuous_mvad.diarized.pause_energy.npy",
    ("v5-diarized_continuous_mvad", "diarized.speaker.npy"): "v5-diarized_continuous_mvad.diarized.speaker.npy",
    ("v5-diarized_mvad", "diarized.vad.npy"): "v5-diarized_mvad.diarized.vad.npy",
    ("v5-diarized_mvad", "diarized.pause_dur.npy"): "v5-diarized_mvad.diarized.pause_dur.npy",
    ("v5-diarized_mvad", "diarized.pause_energy.npy"): "v5-diarized_mvad.diarized.pause_energy.npy",
    ("v5-diarized_mvad", "diarized.speaker.npy"): "v5-diarized_mvad.diarized.speaker.npy",
    # audio quality
    ("acoustic_scores_raw", "c50"): "c50",
    ("acoustic_scores_raw", "dbu"): "dbu",
    ("acoustic_scores_raw", "snr"): "snr",
    ("acoustic_scores_continuous", "c50"): "c50",
    ("acoustic_scores_continuous", "dbu"): "dbu",
    ("acoustic_scores_continuous", "snr"): "snr",
    ("pquality_wmusic_scores_raw", "pq"): "pq",
    ("pquality_wmusic_scores_raw", "music_qual"): "music_qual",
    ("pquality_scores_continuous", "pq"): "pq",
    # tokens
    (
        "dtok_v2_ml_50hz_32x16384_graphemes_key16k", 
        "dtok_level_1_16k.npy"
    ): "dtok_v2_ml_50hz_32x16384_graphemes_key16k.dtok_level_1_16k.npy",
    (
        "dtok_v2_ml_50hz_32x16384_graphemes_key16k",
        "source_start_end_time.npy",
    ): "dtok_v2_ml_50hz_32x16384_graphemes_key16k.source_start_end_time.npy",
    (
        "dtok_v2_ml_50hz_32x16384_graphemes_key16k",
        "boundary_shift_energy.npy",
    ): "dtok_v2_ml_50hz_32x16384_graphemes_key16k.boundary_shift_energy.npy",
    (
        "dtok_v2_ml_50hz_32x16384_graphemes_key16k",
        "vad_boundary_shift.npy",
    ): "dtok_v2_ml_50hz_32x16384_graphemes_key16k.vad_boundary_shift.npy",
    (
        "dtok_v2_ml_50hz_32x16384_graphemes_key16k",
        "vad_original_duration.npy",
    ): "dtok_v2_ml_50hz_32x16384_graphemes_key16k.vad_original_duration.npy",
    (
        "dtok_v2_ml_50hz_32x16384_graphemes_key16k",
        "vad_original_gap.npy",
    ): "dtok_v2_ml_50hz_32x16384_graphemes_key16k.vad_original_gap.npy",
    (
        "dtok_v2_ml_25hz_32x16384_graphemes_v2_encoder",
        "dtok_global.npy",
    ): "dtok_v2_ml_25hz_32x16384_graphemes_v2_encoder.dtok_global.npy",
    (
        "dtok_v2_ml_25hz_32x16384_graphemes_v2_encoder",
        "dtok_level_1.npy",
    ): "dtok_v2_ml_25hz_32x16384_graphemes_v2_encoder.dtok_level_1.npy",
    (
        "dtok_v2_ml_25hz_32x16384_graphemes_v2_encoder",
        "dtok_level_2.npy",
    ): "dtok_v2_ml_25hz_32x16384_graphemes_v2_encoder.dtok_level_2.npy",
    (
        "dtok_v2_ml_25hz_32x16384_graphemes_v2_encoder",
        "source_start_end_time.npy",
    ): "dtok_v2_ml_25hz_32x16384_graphemes_v2_encoder.source_start_end_time.npy",
    (
        "dtok_v2_ml_25hz_32x16384_graphemes_v2_encoder",
        "boundary_shift_energy.npy",
    ): "dtok_v2_ml_25hz_32x16384_graphemes_v2_encoder.boundary_shift_energy.npy",
    (
        "dtok_v2_ml_25hz_32x16384_graphemes_v2_encoder",
        "vad_boundary_shift.npy",
    ): "dtok_v2_ml_25hz_32x16384_graphemes_v2_encoder.vad_boundary_shift.npy",
    (
        "dtok_v2_ml_25hz_32x16384_graphemes_v2_encoder",
        "vad_original_duration.npy",
    ): "dtok_v2_ml_25hz_32x16384_graphemes_v2_encoder.vad_original_duration.npy",
    (
        "dtok_v2_ml_25hz_32x16384_graphemes_v2_encoder",
        "vad_original_gap.npy",
    ): "dtok_v2_ml_25hz_32x16384_graphemes_v2_encoder.vad_original_gap.npy",
    # transcripts
    ("transcription_parakeet-ctc-1-1b_raw", "nemo_transcription.txt"): "nemo_transcription.txt",
    ("transcription_ws_raw", "txt"): "transcription_ws_raw.txt",
    ("transcription_wslang_raw", "txt"): "transcription_wslang_raw.txt",
    ("transcription_wslang_continuous", "txt"): "transcription_wslang_continuous.txt",
    ("transcription_wslang_turbo_raw", "txt"): "transcription_wslang_turbo_raw.txt",
    ("transcription_parakeet-tdt-0-6b-v3_raw", "nemo_transcription.txt"): "transcription_parakeet-tdt-0-6b-v3_raw.txt",
    # ("stoks_raw", "__key__"): "__key__",
    # ("meta_aes_quality_scores_raw", "aes"): "aes",
    # ("atoks_raw", "atoks.npy"): "atoks.npy",
    # ("mos_scores_utmos_raw", "audio_quality"): "audio_quality",
    # ("dac_32c", "dac_32c.npy"): "dac_32c.npy",
    # ("dtok_25hz_vocab_512x3_global_4p4_v2", "dtok_global.npy"): "dtok_25hz_vocab_512x3_global_4p4_v2.dtok_global.npy",
    # ("dtok_25hz_vocab_512x3_global_4p4_v2", "dtok_level_1.npy"): "dtok_25hz_vocab_512x3_global_4p4_v2.dtok_level_1.npy",
    # ("dtok_25hz_vocab_512x3_global_4p4_v2", "dtok_level_2.npy"): "dtok_25hz_vocab_512x3_global_4p4_v2.dtok_level_2.npy",
    # ("dtok_25hz_vocab_512x3_global_4p4_v2", "dtok_level_3.npy"): "dtok_25hz_vocab_512x3_global_4p4_v2.dtok_level_3.npy",
    # ("dtok_prosmimic_48", "dtok_prosmimic_48.npy"): "dtok_prosmimic_48.npy",
    # ("utmos_scores_raw", "duration"): "duration",
    # ("emphasis_raw", "emphassess"): "emphassess",
    # ("clipping_events", "loudness"): "loudness",
    # ("dtok_prosmimic_48", "mean_48.npy"): "mean_48.npy",
    # ("pquality_wmusic_scores_raw", "music_qual"): "music_qual",
    # ("clipping_events", "n_clip_events"): "n_clip_events",
    # ("speaker_activity_raw", "n_speakers"): "n_speakers",
    # ("natmos_v0", "natmos"): "natmos",
    # ("rmvpe_pitch_curve_raw", "pitch_curve.npy"): "pitch_curve.npy",
    # ("pquality_scores_raw", "pq"): "pquality_scores_raw.pq",
    # ("spectral_flatness", "sf_mean"): "sf_mean",
    # ("spectral_flatness", "sf_time"): "sf_time",
    # ("spectral_flatness", "sf_values"): "sf_values",
    # ("speaker_activity_raw", "speaker_activity"): "speaker_activity",
    # ("stoks_raw", "spk_emb.npy"): "spk_emb.npy",
    # ("stoks_raw", "stoks.npy"): "stoks.npy",
    # ("utmos_scores_raw", "utmos"): "utmos",
    # ("vocmimic_raw", "vocmimic"): "vocmimic",
    # ("voxsim", "voxsim.npy"): "voxsim.npy",
    # ("word_alignment_whisperx_raw", "txt"): "word_alignment_whisperx_raw.txt",
    # ("clipping_events", "zcr"): "zcr",
}
