# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuf

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()

# Logically the same as Binary, but the internal representation uses a view
# struct that contains the string length and either the string's entire data
# inline (for small strings) or an inlined prefix, an index of another buffer,
# and an offset pointing to a slice in that buffer (for non-small strings).
#
# Since it uses a variable number of data buffers, each Field with this type
# must have a corresponding entry in `variadicBufferCounts`.
class BinaryView(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsBinaryView(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BinaryView()
        x.Init(buf, n + offset)
        return x

    # BinaryView
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def BinaryViewStart(builder): builder.StartObject(0)
def BinaryViewEnd(builder): return builder.EndObject()
