# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuf

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()

# Same as ListView, but with 64-bit offsets and sizes, allowing to represent
# extremely large data values.
class LargeListView(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsLargeListView(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LargeListView()
        x.Init(buf, n + offset)
        return x

    # LargeListView
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def LargeListViewStart(builder): builder.StartObject(0)
def LargeListViewEnd(builder): return builder.EndObject()
