# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuf

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()

# Contains two child arrays, run_ends and values.
# The run_ends child array must be a 16/32/64-bit integer array
# which encodes the indices at which the run with the value in
# each corresponding index in the values child array ends.
# Like list/struct types, the value array can be of any type.
class RunEndEncoded(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsRunEndEncoded(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RunEndEncoded()
        x.Init(buf, n + offset)
        return x

    # RunEndEncoded
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def RunEndEncodedStart(builder): builder.StartObject(0)
def RunEndEncodedEnd(builder): return builder.EndObject()
